# Generated by Django 5.2.14 on 2026-05-31 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Full script text')),
                ('hook', models.TextField(blank=True)),
                ('text_line', models.CharField(blank=True, help_text='On-screen text (2-4 words + emoji)', max_length=100)),
                ('body', models.TextField(blank=True)),
                ('outro', models.TextField(blank=True)),
                ('word_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('revision', 'In Revision'), ('final', 'Final')], default='draft', max_length=20)),
                ('is_final', models.BooleanField(default=False)),
                ('nick_notes', models.TextField(blank=True, help_text="Nick's feedback/edits for rubric tuning")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField(help_text='Full rules extracted from skill file')),
                ('banned_words', models.JSONField(default=list, help_text='JSON list of banned words')),
                ('rejection_rubric', models.JSONField(default=list, help_text='JSON list of rejection patterns from revision examples')),
                ('min_words', models.IntegerField(default=165)),
                ('max_words', models.IntegerField(default=176)),
                ('min_sentence_words', models.IntegerField(default=12)),
                ('max_sentence_words', models.IntegerField(default=25)),
                ('few_shot_scripts', models.TextField(blank=True, help_text="Paste 3-5 of Nick's best scripts for few-shot prompting")),
                ('artemis_check', models.TextField(blank=True, help_text='The 7-point Artemis voice check criteria')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Config',
                'verbose_name_plural': 'Skill Config',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('topic', models.CharField(blank=True, help_text='science, space, news, etc.', max_length=50)),
                ('trend_score', models.FloatField(default=0)),
                ('virality_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('selected', 'Selected'), ('used', 'Used'), ('skipped', 'Skipped')], default='candidate', max_length=20)),
                ('raw_facts', models.JSONField(default=list, help_text='Facts from Tavily search')),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stories',
                'ordering': ['-trend_score', '-discovered_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('score', models.FloatField(default=0)),
                ('source', models.CharField(default='pytrends', help_text='pytrends or reddit', max_length=50)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='RevisionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_no', models.IntegerField()),
                ('critique', models.JSONField(default=list, help_text='JSON list of objections')),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='scriptgen.script')),
            ],
            options={
                'ordering': ['cycle_no'],
            },
        ),
        migrations.CreateModel(
            name='GenerationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_date', models.DateField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('num_requested', models.IntegerField(default=5)),
                ('num_passed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.TextField(blank=True)),
                ('scripts', models.ManyToManyField(blank=True, related_name='runs', to='scriptgen.script')),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.AddField(
            model_name='script',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='scriptgen.story'),
        ),
        migrations.CreateModel(
            name='ResearchBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(default=list)),
                ('numbers', models.JSONField(default=list)),
                ('orgs', models.JSONField(default=list)),
                ('hook_angles', models.JSONField(default=list)),
                ('sources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research', to='scriptgen.story')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=False)),
                ('body_words', models.IntegerField(default=0)),
                ('hook_words', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('errors', models.JSONField(default=list)),
                ('warnings', models.JSONField(default=list)),
                ('raw_output', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='scriptgen.script')),
            ],
        ),
    ]
